# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CasanareDataExtractDialog
                                 A QGIS plugin
 Plugin para extraer y visualizar datos de Casanare
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-18
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Arnold Mesa
        email                : arnoldjulianmesa@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt import QtCore

# Import info dialog
from .info_dialog import InfoDialog

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'MyPlugin_dialog_base.ui'))



class CasanareDataExtractDialog(QtWidgets.QDialog, FORM_CLASS):
    def _export_pdf(self):
        """Exporta los datos del punto seleccionado a PDF"""
        if self.selected_px is None or self.selected_py is None:
            QtWidgets.QMessageBox.warning(self, "Error", "Debe seleccionar un punto en el mapa primero")
            return
        from qgis.PyQt.QtWidgets import QFileDialog
        import pandas as pd
        import matplotlib.pyplot as plt
        from matplotlib.backends.backend_pdf import PdfPages
        var_idx = self.combo_variable.currentIndex()
        var_map = {
            0: ('Precipitación', self.raster_data_multipp, 'mm'),
            1: ('Temperatura mínima', self.raster_data_multitmin, '°C'),
            2: ('Temperatura máxima', self.raster_data_multitmax, '°C'),
            3: ('Evapotranspiración', self.raster_data_multietp, 'mm')
        }
        var_name, arr, units = var_map[var_idx]
        anio_ini = int(self.combo_anio_inicio.currentText())
        anio_fin = int(self.combo_anio_fin.currentText())
        idx_ini = next(i for i, f in enumerate(self.fechas) if f.year >= anio_ini)
        idx_fin = next(i for i, f in enumerate(self.fechas) if f.year > anio_fin) - 1 if any(f.year > anio_fin for f in self.fechas) else len(self.fechas)-1
        serie = arr[idx_ini:idx_fin+1, self.selected_py, self.selected_px]
        fechas_filtradas = self.fechas[idx_ini:idx_fin+1]
        fechas_str = [f.strftime('%Y-%m-%d') for f in fechas_filtradas]
        import os
        df = pd.DataFrame({
            'Fecha': fechas_str,
            f'{var_name} ({units})': serie,
            'Coordenada_X': [self.selected_coords[0]] * len(serie),
            'Coordenada_Y': [self.selected_coords[1]] * len(serie),
            'Pixel_X': [self.selected_px] * len(serie),
            'Pixel_Y': [self.selected_py] * len(serie)
        })
        filename, _ = QFileDialog.getSaveFileName(
            self, 
            f"Exportar datos de {var_name} a PDF", 
            f"casanare_{var_name.lower().replace(' ', '_')}_{anio_ini}_{anio_fin}.pdf",
            "PDF files (*.pdf)"
        )
        if filename:
            try:
                # Paginación: 30 filas por página, hoja A4, márgenes y variables en cada página
                rows_per_page = 30
                num_rows = len(df)
                num_pages = (num_rows + rows_per_page - 1) // rows_per_page
                a4_inches = (8.27, 11.69)  # A4 size in inches (width, height)
                left_margin = 0.5
                right_margin = 0.5
                top_margin = 1.2  # margen superior mayor para el título
                bottom_margin = 0.7
                table_width = a4_inches[0] - left_margin - right_margin
                table_height = a4_inches[1] - top_margin - bottom_margin
                with PdfPages(filename) as pdf:
                    for page in range(num_pages):
                        start = page * rows_per_page
                        end = min(start + rows_per_page, num_rows)
                        df_page = df.iloc[start:end]
                        fig, ax = plt.subplots(figsize=a4_inches)
                        ax.axis('off')
                        # Título con variables
                        title_text = (f"Datos seleccionados - {var_name} ({units})\n"
                                      f"Coordenada: {self.selected_coords[0]:.4f}, {self.selected_coords[1]:.4f}\n"
                                      f"Rango: {anio_ini}-{anio_fin} | Página {page+1} de {num_pages}")
                        plt.title(title_text, fontsize=12, loc='left', pad=20)
                        # Tabla
                        table = ax.table(cellText=df_page.values,
                                         colLabels=df_page.columns,
                                         loc='center',
                                         cellLoc='center',
                                         bbox=[left_margin/a4_inches[0], (top_margin+0.1)/a4_inches[1],
                                               table_width/a4_inches[0], (table_height-0.2)/a4_inches[1]])
                        table.auto_set_font_size(False)
                        table.set_fontsize(7)
                        table.scale(1.15, 1.25)
                        # Ajustar ancho de columnas para evitar solapamientos
                        for key, cell in table.get_celld().items():
                            cell.set_width(1.0 / len(df_page.columns))
                        plt.subplots_adjust(left=left_margin/a4_inches[0],
                                           right=1-right_margin/a4_inches[0],
                                           top=1-top_margin/a4_inches[1],
                                           bottom=bottom_margin/a4_inches[1])
                        pdf.savefig(fig)
                        plt.close(fig)
                QtWidgets.QMessageBox.information(self, "Éxito", f"Datos exportados correctamente a:\n{filename}")
            except Exception as e:
                QtWidgets.QMessageBox.critical(self, "Error", f"No se pudo exportar el archivo PDF:\n{str(e)}")
    def _export_excel(self):
        """Exporta los datos del punto seleccionado a Excel (.xlsx)"""
        if self.selected_px is None or self.selected_py is None:
            QtWidgets.QMessageBox.warning(self, "Error", "Debe seleccionar un punto en el mapa primero")
            return
        from qgis.PyQt.QtWidgets import QFileDialog
        import pandas as pd
        var_idx = self.combo_variable.currentIndex()
        var_map = {
            0: ('Precipitación', self.raster_data_multipp, 'mm'),
            1: ('Temperatura mínima', self.raster_data_multitmin, '°C'),
            2: ('Temperatura máxima', self.raster_data_multitmax, '°C'),
            3: ('Evapotranspiración', self.raster_data_multietp, 'mm')
        }
        var_name, arr, units = var_map[var_idx]
        anio_ini = int(self.combo_anio_inicio.currentText())
        anio_fin = int(self.combo_anio_fin.currentText())
        idx_ini = next(i for i, f in enumerate(self.fechas) if f.year >= anio_ini)
        idx_fin = next(i for i, f in enumerate(self.fechas) if f.year > anio_fin) - 1 if any(f.year > anio_fin for f in self.fechas) else len(self.fechas)-1
        serie = arr[idx_ini:idx_fin+1, self.selected_py, self.selected_px]
        fechas_filtradas = self.fechas[idx_ini:idx_fin+1]
        fechas_str = [f.strftime('%Y-%m-%d') for f in fechas_filtradas]
        import os
        df = pd.DataFrame({
            'Fecha': fechas_str,
            f'{var_name} ({units})': serie,
            'Coordenada_X': [self.selected_coords[0]] * len(serie),
            'Coordenada_Y': [self.selected_coords[1]] * len(serie),
            'Pixel_X': [self.selected_px] * len(serie),
            'Pixel_Y': [self.selected_py] * len(serie)
        })
        filename, _ = QFileDialog.getSaveFileName(
            self, 
            f"Exportar datos de {var_name} a Excel", 
            f"casanare_{var_name.lower().replace(' ', '_')}_{anio_ini}_{anio_fin}.xlsx",
            "Excel files (*.xlsx)"
        )
        if filename:
            try:
                df.to_excel(filename, index=False)
                QtWidgets.QMessageBox.information(self, "Éxito", f"Datos exportados correctamente a:\n{filename}")
            except Exception as e:
                QtWidgets.QMessageBox.critical(self, "Error", f"No se pudo exportar el archivo Excel:\n{str(e)}")
    def _export_csv(self):
        """Exporta los datos del punto seleccionado a CSV"""
        if self.selected_px is None or self.selected_py is None:
            QtWidgets.QMessageBox.warning(self, "Error", "Debe seleccionar un punto en el mapa primero")
            return
        from qgis.PyQt.QtWidgets import QFileDialog
        import pandas as pd
        var_idx = self.combo_variable.currentIndex()
        var_map = {
            0: ('Precipitación', self.raster_data_multipp, 'mm'),
            1: ('Temperatura mínima', self.raster_data_multitmin, '°C'),
            2: ('Temperatura máxima', self.raster_data_multitmax, '°C'),
            3: ('Evapotranspiración', self.raster_data_multietp, 'mm')
        }
        var_name, arr, units = var_map[var_idx]
        anio_ini = int(self.combo_anio_inicio.currentText())
        anio_fin = int(self.combo_anio_fin.currentText())
        idx_ini = next(i for i, f in enumerate(self.fechas) if f.year >= anio_ini)
        idx_fin = next(i for i, f in enumerate(self.fechas) if f.year > anio_fin) - 1 if any(f.year > anio_fin for f in self.fechas) else len(self.fechas)-1
        serie = arr[idx_ini:idx_fin+1, self.selected_py, self.selected_px]
        fechas_filtradas = self.fechas[idx_ini:idx_fin+1]
        fechas_str = [f.strftime('%Y-%m-%d') for f in fechas_filtradas]
        import os
        df = pd.DataFrame({
            'Fecha': fechas_str,
            f'{var_name} ({units})': serie,
            'Coordenada_X': [self.selected_coords[0]] * len(serie),
            'Coordenada_Y': [self.selected_coords[1]] * len(serie),
            'Pixel_X': [self.selected_px] * len(serie),
            'Pixel_Y': [self.selected_py] * len(serie)
        })
        filename, _ = QFileDialog.getSaveFileName(
            self, 
            f"Exportar datos de {var_name}", 
            f"casanare_{var_name.lower().replace(' ', '_')}_{anio_ini}_{anio_fin}.csv",
            "CSV files (*.csv)"
        )
        if filename:
            try:
                df.to_csv(filename, index=False, encoding='utf-8')
                QtWidgets.QMessageBox.information(self, "Éxito", f"Datos exportados correctamente a:\n{filename}")
            except Exception as e:
                QtWidgets.QMessageBox.critical(self, "Error", f"No se pudo exportar el archivo:\n{str(e)}")

    def _export_png(self):
        """Exporta la gráfica actual como imagen PNG"""
        if self.selected_px is None or self.selected_py is None:
            QtWidgets.QMessageBox.warning(self, "Error", "Debe seleccionar un punto en el mapa primero")
            return
        from qgis.PyQt.QtWidgets import QFileDialog
        var_idx = self.combo_variable.currentIndex()
        var_names = ['precipitacion', 'temperatura_minima', 'temperatura_maxima', 'evapotranspiracion']
        var_name = var_names[var_idx]
        anio_ini = int(self.combo_anio_inicio.currentText())
        anio_fin = int(self.combo_anio_fin.currentText())
        filename, _ = QFileDialog.getSaveFileName(
            self, 
            "Exportar gráfica como PNG", 
            f"grafica_{var_name}_{anio_ini}_{anio_fin}.png",
            "PNG files (*.png)"
        )
        if filename:
            try:
                self.fig.savefig(filename, dpi=300, bbox_inches='tight', facecolor='white', edgecolor='none')
                QtWidgets.QMessageBox.information(self, "Éxito", f"Gráfica exportada correctamente a:\n{filename}")
            except Exception as e:
                QtWidgets.QMessageBox.critical(self, "Error", f"No se pudo exportar la imagen:\n{str(e)}")
    
    def _show_info(self):
        """Muestra la ventana de información del plugin"""
        try:
            info_dialog = InfoDialog(self)
            info_dialog.exec_()
        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Error", f"No se pudo abrir la ventana de información:\n{str(e)}")
    
    def __init__(self, parent=None):
        """Constructor."""
        super(CasanareDataExtractDialog, self).__init__(parent)
        self.setupUi(self)
        # Hacer el diálogo redimensionable y maximizable
        self.setWindowFlags(self.windowFlags() | QtCore.Qt.WindowMaximizeButtonHint | QtCore.Qt.WindowMinimizeButtonHint)
        self.resize(800, 600)  # Tamaño inicial más grande
        # Conectar búsqueda por coordenadas manuales
        self.lineEdit_X = self.findChild(QtWidgets.QLineEdit, 'lineEdit_X')
        self.lineEdit_Y = self.findChild(QtWidgets.QLineEdit, 'lineEdit_Y')
        self.pushButton_show = self.findChild(QtWidgets.QPushButton, 'pushButton_show')
        if self.pushButton_show:
            self.pushButton_show.clicked.connect(self._buscar_por_coordenadas)
        # Conectar botones de exportación con verificación de depuración
        try:
            if hasattr(self, 'pushButton_exportCsv'):
                self.pushButton_exportCsv.clicked.connect(self._export_csv)
                print("✓ Botón CSV conectado correctamente")
            else:
                print("✗ Error: pushButton_exportCsv no encontrado")
            if hasattr(self, 'pushButton_exportPng'):
                self.pushButton_exportPng.clicked.connect(self._export_png)
                print("✓ Botón PNG conectado correctamente")
            else:
                print("✗ Error: pushButton_exportPng no encontrado")
            if hasattr(self, 'pushButton_exportExcel'):
                self.pushButton_exportExcel.clicked.connect(self._export_excel)
                print("✓ Botón Excel conectado correctamente")
            else:
                print("✗ Error: pushButton_exportExcel no encontrado")
            if hasattr(self, 'pushButton_exportPdf'):
                self.pushButton_exportPdf.clicked.connect(self._export_pdf)
                print("✓ Botón PDF conectado correctamente")
            else:
                print("✗ Error: pushButton_exportPdf no encontrado")
            if hasattr(self, 'pushButton_exportExcel'):
                self.pushButton_exportExcel.clicked.connect(self._export_excel)
                print("✓ Botón Excel conectado correctamente")
            else:
                print("✗ Error: pushButton_exportExcel no encontrado")
            # Conectar botón de información
            if hasattr(self, 'pushButton_info'):
                self.pushButton_info.clicked.connect(self._show_info)
                print("✓ Botón Información conectado correctamente")
            else:
                print("✗ Error: pushButton_info no encontrado")
        except Exception as e:
            print(f"Error al conectar botones: {e}")
        # --- Matplotlib embebido ---
        from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
        import matplotlib.pyplot as plt
        import numpy as np
        import os
        self.np = np
        self.plt = plt
        self.FigureCanvas = FigureCanvas
        # Cargar arrays tridimensionales con verificación
        # Obtener el directorio del plugin de forma dinámica
        plugin_dir = os.path.dirname(__file__)
        rutas_abs = {
            'raster_data_multipp.npy': os.path.join(plugin_dir, 'PluginQgis', 'raster_data_multipp.npy'),
            'raster_data_multitmin.npy': os.path.join(plugin_dir, 'PluginQgis', 'raster_data_multitmin.npy'),
            'raster_data_multitmax.npy': os.path.join(plugin_dir, 'PluginQgis', 'raster_data_multitmax.npy'),
            'raster_data_multietp.npy': os.path.join(plugin_dir, 'PluginQgis', 'raster_data_multietp.npy')
        }
        faltantes = []
        for fname, ruta in rutas_abs.items():
            if not os.path.exists(ruta):
                faltantes.append(f"{fname}: {ruta}")
        if faltantes:
            msg = ("No se encontraron los siguientes archivos de datos:\n" +
                   '\n'.join(faltantes) +
                   "\n\nColóquelos en la carpeta PluginQgis dentro del plugin para habilitar la funcionalidad.")
            QtWidgets.QMessageBox.warning(self, "Archivos faltantes", msg)
            self.setEnabled(False)
            return
        self.raster_data_multipp = np.load(rutas_abs['raster_data_multipp.npy'])
        self.raster_data_multitmin = np.load(rutas_abs['raster_data_multitmin.npy'])
        self.raster_data_multitmax = np.load(rutas_abs['raster_data_multitmax.npy'])
        self.raster_data_multietp = np.load(rutas_abs['raster_data_multietp.npy'])
        # Parámetros cartográficos
        self.topLeftX = -73.125
        self.CelSize = 0.041666666666666664
        self.topLeftY = 6.375
        self.pixelHeight = -0.041666666666666664
        # Fechas para los 504 meses (enero 1981 - diciembre 2022)
        from datetime import datetime, timedelta
        start_date = datetime(1981, 1, 1)
        self.fechas = [start_date + timedelta(days=30.44*i) for i in range(504)]
        self.fechas_str = [fecha.strftime('%Y-%m') for fecha in self.fechas]
        self.anios = sorted(list(set([fecha.year for fecha in self.fechas])))
        # Poblar combos de años
        self.combo_anio_inicio.addItems([str(a) for a in self.anios])
        self.combo_anio_fin.addItems([str(a) for a in self.anios])
        self.combo_anio_inicio.setCurrentIndex(0)
        self.combo_anio_fin.setCurrentIndex(len(self.anios)-1)
        # --- Matplotlib Figure ---
        self.fig, self.ax = plt.subplots(figsize=(5, 3))
        self.canvas = FigureCanvas(self.fig)
        from qgis.PyQt.QtWidgets import QScrollArea
        from qgis.PyQt.QtCore import Qt
        self.scroll_grafica = QScrollArea()
        self.scroll_grafica.setWidget(self.canvas)
        self.scroll_grafica.setWidgetResizable(True)
        self.scroll_grafica.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.layout().addWidget(self.scroll_grafica)
        self.label_grafica.hide()  # Ocultar QLabel, usar canvas
        # Mostrar mapa base en QLabel
        self.mapa_base = self.raster_data_multipp[0, :, :]
        # Estado actual (debe ir antes de usar en _update_map_pixmap)
        self.selected_px = None
        self.selected_py = None
        self.selected_coords = None
        self._update_map_pixmap()
        # Conectar eventos
        self.label_map.mousePressEvent = self._on_map_click
        self.combo_variable.currentIndexChanged.connect(self._update_plot)
        self.combo_anio_inicio.currentIndexChanged.connect(self._update_plot)
        self.combo_anio_fin.currentIndexChanged.connect(self._update_plot)
        # Botón para cambiar a mapa de calor debajo del mapa
        self.pushButton_heatmap = QtWidgets.QPushButton()
        self.pushButton_heatmap.setText('Cambiar Color')
        # Ubicar el botón debajo del mapa en el layout principal
        main_layout = self.findChild(QtWidgets.QVBoxLayout, 'verticalLayout_main')
        if main_layout:
            # Buscar el índice del label_map y agregar el botón después
            for i in range(main_layout.count()):
                item = main_layout.itemAt(i)
                widget = item.widget() if item else None
                if widget and widget.objectName() == 'label_map':
                    main_layout.insertWidget(i+1, self.pushButton_heatmap)
                    break
            else:
                main_layout.addWidget(self.pushButton_heatmap)
        else:
            self.layout().addWidget(self.pushButton_heatmap)

        # Agregar los campos de coordenadas manuales al panel derecho (verticalLayout_controls)
        controls_layout = self.findChild(QtWidgets.QVBoxLayout, 'verticalLayout_controls')
        if controls_layout:
            self.label_coord_manual = QtWidgets.QLabel('Ingresar coordenadas manualmente:')
            controls_layout.addWidget(self.label_coord_manual)
            self.lineEdit_X = QtWidgets.QLineEdit()
            self.lineEdit_X.setPlaceholderText('Ejemplo: -72.5')
            self.lineEdit_X.setToolTip('Coordenada X (longitud)')
            controls_layout.addWidget(self.lineEdit_X)
            self.lineEdit_Y = QtWidgets.QLineEdit()
            self.lineEdit_Y.setPlaceholderText('Ejemplo: 5.8')
            self.lineEdit_Y.setToolTip('Coordenada Y (latitud)')
            controls_layout.addWidget(self.lineEdit_Y)
            self.pushButton_show = QtWidgets.QPushButton('Buscar por coordenadas')
            self.pushButton_show.setToolTip('Buscar el punto en el mapa usando las coordenadas ingresadas')
            controls_layout.addWidget(self.pushButton_show)
            self.pushButton_show.clicked.connect(self._buscar_por_coordenadas)
        self.heatmap_mode = False
        self.pushButton_heatmap.clicked.connect(self._toggle_heatmap)

    def _toggle_heatmap(self):
        self.heatmap_mode = not self.heatmap_mode
        self._update_map_pixmap()

    def _update_map_pixmap(self):
        import matplotlib.pyplot as plt
        import numpy as np
        from qgis.PyQt.QtGui import QPixmap, QImage, QPainter, QColor
        from qgis.PyQt.QtCore import Qt
        
        arr = self.mapa_base
        mask_valid = ~np.isnan(arr)
        h, w = arr.shape
        rgb_array = np.zeros((h, w, 3), dtype=np.uint8)
        arr_valid = arr[mask_valid]
        if arr_valid.size > 0:
            arr_norm = (arr_valid - np.nanmin(arr_valid)) / (np.nanmax(arr_valid) - np.nanmin(arr_valid) + 1e-8)
            if hasattr(self, 'heatmap_mode') and self.heatmap_mode:
                cmap = plt.get_cmap('hot')  # Mapa de calor
            else:
                cmap = plt.get_cmap('Blues')  # Tonos de azul
            colors = (cmap(arr_norm)[:, :3] * 255).astype(np.uint8)
            rgb_array[mask_valid] = colors
        rgb_array[~mask_valid] = [0, 0, 0]
        qimg = QImage(rgb_array.data, w, h, w * 3, QImage.Format_RGB888)
        pixmap = QPixmap.fromImage(qimg).scaled(self.label_map.width(), self.label_map.height())

        # Dibuja el punto rojo si hay selección (más grande y visible)
        if self.selected_px is not None and self.selected_py is not None:
            painter = QPainter(pixmap)
            painter.setRenderHint(QPainter.Antialiasing)
            
            # Punto rojo con borde negro para mayor visibilidad
            painter.setPen(QColor(0, 0, 0, 255))  # Borde negro
            painter.setBrush(QColor(255, 0, 0, 255))  # Relleno rojo
            
            # Convertir coordenadas de matriz a pixmap
            x = int(self.selected_px / w * self.label_map.width())
            y = int(self.selected_py / h * self.label_map.height())
            
            # Punto más grande y visible
            painter.drawEllipse(x-6, y-6, 12, 12)
            painter.end()

        self.label_map.setPixmap(pixmap)

    def _on_map_click(self, event):
        x = event.pos().x()
        y = event.pos().y()
        w = self.label_map.width()
        h = self.label_map.height()
        arr = self.mapa_base
        arr_h, arr_w = arr.shape
        px = int(x / w * arr_w)
        py = int(y / h * arr_h)
        x_coord = self.topLeftX + px * self.CelSize
        y_coord = self.topLeftY + py * self.pixelHeight
        self.selected_px = px
        self.selected_py = py
        self.selected_coords = (x_coord, y_coord)
        self.label_coords.setText(f"Coordenadas: {x_coord:.4f}, {y_coord:.4f}")
        self._update_map_pixmap()  # Actualiza el mapa con el punto rojo
        self._update_plot()

    def _buscar_por_coordenadas(self):
        try:
            x_coord = float(self.lineEdit_X.text())
            y_coord = float(self.lineEdit_Y.text())
        except Exception:
            QtWidgets.QMessageBox.warning(self, "Error", "Ingrese coordenadas válidas (números decimales)")
            return
        px = int((x_coord - self.topLeftX) / self.CelSize)
        py = int((y_coord - self.topLeftY) / self.pixelHeight)
        arr = self.mapa_base
        arr_h, arr_w = arr.shape
        if not (0 <= px < arr_w and 0 <= py < arr_h):
            QtWidgets.QMessageBox.warning(self, "Error", "Las coordenadas están fuera del área de Casanare")
            return
        self.selected_px = px
        self.selected_py = py
        self.selected_coords = (x_coord, y_coord)
        self.label_coords.setText(f"Coordenadas: {x_coord:.4f}, {y_coord:.4f}")
        self._update_map_pixmap()  # Actualiza el mapa con el punto rojo
        self._update_plot()

    def _update_plot(self):
        if self.selected_px is None or self.selected_py is None:
            self.ax.clear()
            self.ax.text(0.5, 0.5, 'Seleccione un punto en el mapa', ha='center', va='center')
            self.canvas.draw()
            return
        var_idx = self.combo_variable.currentIndex()
        var_map = {
            0: ('Precipitación', self.raster_data_multipp),
            1: ('Temperatura mínima', self.raster_data_multitmin),
            2: ('Temperatura máxima', self.raster_data_multitmax),
            3: ('Evapotranspiración', self.raster_data_multietp)
        }
        var_name, arr = var_map[var_idx]
        anio_ini = int(self.combo_anio_inicio.currentText())
        anio_fin = int(self.combo_anio_fin.currentText())
        idx_ini = next(i for i, f in enumerate(self.fechas) if f.year >= anio_ini)
        idx_fin = next(i for i, f in enumerate(self.fechas) if f.year > anio_fin) - 1 if any(f.year > anio_fin for f in self.fechas) else len(self.fechas)-1
        serie = arr[idx_ini:idx_fin+1, self.selected_py, self.selected_px]
        fechas = self.fechas_str[idx_ini:idx_fin+1]
        self.ax.clear()
        # Ajustar el ancho del canvas para permitir scroll si hay muchas fechas
        ancho = max(400, 20 * len(fechas))
        self.canvas.setMinimumWidth(ancho)
        self.ax.plot(fechas, serie, marker='o', linestyle='-', linewidth=1,
            color='red' if 'Temperatura' in var_name else 'blue')
        self.ax.set_title(f'{var_name} en ({self.selected_coords[0]:.4f}, {self.selected_coords[1]:.4f})')
        self.ax.set_xlabel('Fecha')
        self.ax.set_ylabel(var_name)
        self.ax.tick_params(axis='x', labelrotation=45)
        self.ax.grid(True, alpha=0.3)
        if 'Temperatura' in var_name:
            self.ax.yaxis.set_major_formatter(self.plt.FuncFormatter(lambda x, _: f'{x:.2f}'))
        self.fig.tight_layout()
        self.canvas.draw()